from django.conf.urls.defaults import patterns, url
from django.contrib.auth.views import *

urlpatterns = patterns("account.views",
    url(r'^$', 'index', 
        name='account_home'),
    url(r'^profile/$', 'index', 
        name='account_home_index'),
    url(r'^register/$', 'register_user', 
        name='register'), 
    url(r'^update-profile/$', 'update_profile', 
        name='update_profile'),
    url(r'^change-email/$', 'change_email', 
        name='change_email'),
    url(r'^activate-email/(?P<activation_key>.+)/$', 'activate_email', 
        name='activate_email'),
    url(r'^activate-account/(?P<activation_key>.+)/$', 'activate_account', 
        name='activate_account'),
    url(r'^my-posts/$', 'my_posts', name='my_posts'),
    url(r'^message/$', 'message', name='message'),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', 
        name='login'),
    url(r'^logout/$', 'logout', 
        name='logout'),
    url(r'^password_change/$', 'password_change', 
        name='password_change'),
    url(r'^password_change/done/$', 'password_change_done', 
        name='password_change_done'),
    url(r'^password_reset/$', 'password_reset', 
        name='password_reset'),
    url(r'^password_reset/done/$', 'password_reset_done', 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'password_reset_complete', 
        name='password_reset_complete'),
)